In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

import warnings
warnings.filterwarnings('ignore')

# para pintar
import pylab as plt
import seaborn as sns

# para que salga el grafico
%matplotlib inline

In [2]:
dogs = pd.read_csv('../data/archivo/dog_breeds.csv', encoding = "ISO-8859-1")

In [3]:
dogs.shape

(117, 8)

In [4]:
dogs.columns

Index(['Breed', 'Country of Origin', 'Fur Color', 'Height (in)',
       'Color of Eyes', 'Longevity (yrs)', 'Character Traits',
       'Common Health Problems'],
      dtype='object')

In [5]:
dogs.head()

,Breed,Country of Origin,Fur Color,Height (in),Color of Eyes,Longevity (yrs),Character Traits,Common Health Problems
0,Labrador Retriever,Canada,"Yellow, Black, Chocolate",21-24,Brown,10-12,"Loyal, friendly, intelligent, energetic, good-...","Hip dysplasia, obesity, ear infections"
1,German Shepherd,Germany,"Black, Tan",22-26,Brown,7-10,"Loyal, intelligent, protective, confident, tra...","Hip dysplasia, elbow dysplasia, pancreatitis"
2,Bulldog,England,"White, Red",12-16,Brown,8-10,"Loyal, calm, gentle, brave","Skin allergies, respiratory issues, obesity"
3,Poodle,France,"White, Black, Brown, Apricot",10-15,"Brown, Blue",12-15,"Intelligent, active, affectionate, hypoallergenic","Hip dysplasia, epilepsy, bladder stones"
4,Beagle,England,"White, Tan, Red, Lemon",13-15,Brown,12-15,"Curious, friendly, energetic, good-natured","Ear infections, hip dysplasia, epilepsy"

In [6]:
dogs.tail()

,Breed,Country of Origin,Fur Color,Height (in),Color of Eyes,Longevity (yrs),Character Traits,Common Health Problems
112,Catahoula Leopard Dog,United States,"Merle, Black",20-26,Brown,12-14,"Intelligent, energetic, good-natured, loyal","Dental problems, eye issues, skin allergies"
113,Cocker Spaniel,England,"Black, Brown",14-15,Brown,12-15,"Intelligent, energetic, playful, good-natured","Dental problems, eye issues, skin allergies"
114,Miniature Shiba Inu,Japan,"Red, Sesame",13-16,Brown,12-15,"Intelligent, energetic, playful, good-natured","Dental problems, eye issues, skin allergies"
115,Belgian Tervuren,Belgium,Fawn,22-26,Brown,12-14,"Intelligent, energetic, good-natured, loyal","Dental problems, eye issues, skin allergies"
116,Pharaoh Hound,Malta,Red,21-25,Brown,12-14,"Intelligent, energetic, good-natured, loyal","Dental problems, eye issues, skin allergies"

In [26]:
dogin = pd.read_csv('../data/archivo/dog_intelligence.csv', encoding = "ISO-8859-1")

In [27]:
dogin.shape

(150, 7)

In [28]:
dogin.head()

,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,reps_lower,reps_upper
0,Akita,26.0,28.0,80,120,1.0,4.0
1,A0tolian Sheepdog,27.0,29.0,100,150,1.0,4.0
2,Bernese Mountain Dog,23.0,27.0,85,110,1.0,4.0
3,Bloodhound,24.0,26.0,80,120,1.0,4.0
4,Borzoi,26.0,28.0,70,100,1.0,4.0

In [31]:
dogin.tail(50) #Hay que limpiar las filas que tengan nulos en las dos ultimas columnas
            #Que cuadren con el primer dataFrame (dogs)
            #Añadir una columna que haga un ranking de los perros por raza más inteligente
        #https://www.traveler.es/experiencias/articulos/mapa-razas-de-perro-mas-populares-buscadas-del-mundo/20277

,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,reps_lower,reps_upper
100,Australian Terrier,10.0,10.0,10,14,26.0,40.0
101,Basenji,17.0,17.0,20,22,26.0,40.0
102,Beagle,13.0,16.0,18,30,26.0,40.0
103,Bedlington Terrier,15.0,16.0,18,23,41.0,80.0
104,Bichon Frise,9.5,11.5,10,18,41.0,80.0
105,Border Terrier,12.0,15.0,12,15,41.0,80.0
106,Boston Terrier,14.0,15.0,15,25,41.0,80.0
107,Brussels Griffon,7.0,8.0,6,12,41.0,80.0
108,Cairn Terrier,9.0,10.0,14,14,41.0,80.0
109,Cardigan Welsh Corgi,10.0,12.0,25,35,41.0,80.0
110,Cavalier King Charles Spaniel,10.0,15.0,15,20,41.0,80.0
111,Coton de Tulear,0.0,0.0,0,0,41.0,80.0
112,Dachshund,7.0,10.0,16,32,41.0,80.0
113,Dandie Dinmont Terrier,18.0,24.0,8,11,41.0,80.0
114,English Toy Spaniel,10.0,10.0,9,15,41.0,80.0
115,Fox Terrier ÛÒ Smooth,13.0,16.0,15,20,41.0,80.0
116,Fox Terrier ÛÒ Wirehair,13.0,16.0,15,20,41.0,80.0
117,French Bulldog,11.0,12.0,17,28,41.0,80.0
118,German Pinscher,16.0,19.0,25,35,41.0,80.0
119,Glen Imaal Terrier,14.0,14.0,34,36,41.0,80.0
120,Lakeland Terrier,13.0,14.0,15,17,41.0,80.0
121,Manchester Terrier (Standard),15.0,16.0,17,18,41.0,80.0
122,Poodle Miniature,10.0,15.0,20,20,41.0,80.0
123,Pug,10.0,11.0,14,22,41.0,80.0
124,Puli,16.0,17.0,29,33,41.0,80.0
125,Schipperke,10.0,13.0,12,18,81.0,100.0
126,Scottish Terrier,10.0,12.0,18,22,81.0,100.0
127,Sealyham Terrier,12.0,12.0,18,20,81.0,100.0
128,Shetland Sheepdog (Sheltie),13.0,16.0,14,20,81.0,100.0
129,Shiba Inu,13.0,16.0,15,30,81.0,100.0
130,Shih Tzu,8.0,11.0,9,16,81.0,100.0
131,Silky Terrier,9.0,10.0,8,11,81.0,100.0
132,Skye Terrier,10.0,10.0,25,25,81.0,100.0
133,Tibetan Spaniel,10.0,10.0,9,15,81.0,100.0
134,Tibetan Terrier,14.0,17.0,20,30,81.0,100.0
135,Welsh Terrier,15.0,15.0,20,21,81.0,100.0
136,West Highland White Terrier,11.0,11.0,13,15,NaN,NaN
137,Whippet,18.0,22.0,27,30,NaN,NaN
138,Affenpinscher,9.0,12.0,8,12,NaN,NaN
139,Chihuahua,6.0,9.0,2,5,NaN,NaN
140,Chinese Crested,11.0,13.0,5,12,NaN,NaN
141,Italian Greyhound,12.0,15.0,6,10,NaN,NaN
142,Japanese Chin,8.0,11.0,4,11,NaN,NaN
143,Maltese,8.0,10.0,4,6,NaN,NaN
144,Manchester Terrier (Toy),10.0,12.0,6,8,NaN,NaN
145,Papillon,8.0,11.0,5,10,NaN,NaN
146,Pomeranian,12.0,12.0,3,7,NaN,NaN
147,Poodle Toy,10.0,10.0,10,10,NaN,NaN
148,Toy Fox Terrier,10.0,10.0,4,7,NaN,NaN
149,Yorkshire Terrier,8.0,8.0,3,7,NaN,NaN

In [30]:
dogin.columns

Index(['Breed', 'height_low_inches', 'height_high_inches', 'weight_low_lbs',
       'weight_high_lbs', 'reps_lower', 'reps_upper'],
      dtype='object')

In [ ]:
#The lower limit of repetitions to understand new commands.
#The upper limit of repetitions to understand new commands.
#ESTO SI https://www.finder.com/most-popular-dog-breeds